#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env = env.Clone()

# Enable module support
env.Append(CCFLAGS=["-fmodules", "-fcxx-modules"])

# Use bundled Vulkan headers
vulkan_dir = "#thirdparty/vulkan"
env.Prepend(CPPPATH=[vulkan_dir, vulkan_dir + "/include"])

# Driver source files
env.add_source_files(env.drivers_sources, "*.mm")
